import type { ReactNode } from "react";
import type { ConversationReplyResult, DriveTeammateResult, FirmActiveDrive } from "@/api";
import type { CanvasSelection } from "@/components/firm/directionTarget";
import type { ProductGtmWalkthroughStep } from "@/components/product-gtm/productGtmWorkflow";
import type { ArtifactSectionFocus } from "@/components/review/artifactSectionFocus";
import type { FirmConfiguration } from "@/types";

export type NowComposerProps = {
  ventureId: string;
  ventureName: string;
  selection: CanvasSelection;
  scopeLabel: string | null;
  hasWork: boolean;
  variant?: "hero" | "dock";
  readOnly?: boolean;
  readOnlyReason?: string | null;
  autoFocus?: boolean;
  focusRequest?: number;
  placeholder?: string;
  submissionMode?: "auto" | "conversation" | "work" | "product-gtm";
  onClearScope?: () => void;
  onSubmitStart?: (message: string) => void;
  onSubmitAccepted?: (message: string, result: ConversationReplyResult) => void;
  onSubmitFailed?: (message: string) => void;
  onDriven?: (result?: DriveTeammateResult) => void;
  onWorkRouted?: (threadRef: string) => void;
  onOpenResult?: (targetBetId: string | null) => void;
  subjectRefs?: string[];
  runtimeOverride?: string | null;
  modelOverride?: string | null;
  effortOverride?: string | null;
  composerControls?: ReactNode;
  configuration?: FirmConfiguration | null;
  productGtmView?: boolean;
  workflowSketch?: boolean;
  modelBranchRef?: string | null;
  artifactSection?: ArtifactSectionFocus | null;
  onClearArtifactSection?: () => void;
  workflowStep?: ProductGtmWalkthroughStep | null;
  repositoryFiles?: string[];
  activeDrive?: FirmActiveDrive | null;
  journeyImportEnabled?: boolean;
};
