/* Re-vendor the showcase's generated runtime assets from the design-system build.
   The showcase reads the package stylesheet directly. Its component IIFE
   (window.GtmIde) and fonts come from ../ds-bundle, which is gitignored and
   regenerated by the converter. Run this after a build:

     node design-system/.ds-sync/package-build.mjs --config ... --out ./ds-bundle
     node design-system/showcase/refresh-assets.cjs
*/
const fs = require("fs");
const path = require("path");

const SH = __dirname;
const DB = path.join(SH, "..", "ds-bundle");

if (!fs.existsSync(DB)) {
  console.error("ds-bundle/ not found — run the converter build first (see header).");
  process.exit(1);
}
fs.copyFileSync(path.join(DB, "_ds_bundle.js"), path.join(SH, "_ds_bundle.js"));
fs.rmSync(path.join(SH, "fonts"), { recursive: true, force: true });
fs.cpSync(path.join(DB, "fonts"), path.join(SH, "fonts"), { recursive: true });
console.log("refreshed _ds_bundle.js + fonts/ from ../ds-bundle");
