/* Re-vendor the showcase's runtime assets from the design-system build.
   The showcase is a static page; it needs the built stylesheet, the component
   IIFE (window.GtmIde), and the fonts co-located. Those come from ../ds-bundle,
   which is gitignored and regenerated by the converter. Run this after a build:

     node design-system/.ds-sync/package-build.mjs --config ... --out ./ds-bundle
     node design-system/showcase/refresh-assets.cjs
*/
const fs = require("fs");
const path = require("path");

const SH = __dirname;
const DB = path.join(SH, "..", "ds-bundle");

if (!fs.existsSync(DB)) {
  console.error("ds-bundle/ not found — run the converter build first (see header).");
  process.exit(1);
}
for (const f of ["styles.css", "_ds_bundle.css", "_ds_bundle.js"]) {
  fs.copyFileSync(path.join(DB, f), path.join(SH, f));
}
fs.rmSync(path.join(SH, "fonts"), { recursive: true, force: true });
fs.cpSync(path.join(DB, "fonts"), path.join(SH, "fonts"), { recursive: true });
console.log("refreshed styles.css + _ds_bundle.css + _ds_bundle.js + fonts/ from ../ds-bundle");
