import { useState } from "react";
import {
  ArrowRight, Boxes, FileCode2, GitBranch, LoaderCircle, Radio, Sparkles, Target, Workflow,
} from "lucide-react";
import type {
  ProductModel, ProductModelEdit, ProductThing, ProductRelationship, ProductUserGoal,
  ProductStateElement,
} from "@/types";

// The Living Product Picture — the founder-editable INTERPRETATION layer that sits on top of the
// cited scan truth. It renders the product's things / relationships / user goals / states plus the
// pinned real-world signals, and every edit persists through the domain commands (revise/derive),
// then re-fetches so the surface always reflects the current projected version. This is
// interpretation, never truth: the scan (ProductUnderstanding) stays the cited-fact map; this adds
// the conceptual shape that truth deliberately lacks.

// Provenance is shown inline so a speculative guess never reads as a cited fact (mirrors the
// provider's anti-pollution framing at the consumption point).
function ProvenanceTag({ provenance }: { provenance: "derived" | "speculative" }) {
  return (
    <span className={`pp-prov pp-prov-${provenance}`} title={provenance === "derived" ? "Cites real file:line" : "Founder/model guess — not proven from code"}>
      {provenance}
    </span>
  );
}

export function ProductPicture({
  model,
  busy,
  productName,
  onDerive,
  onRevise,
}: {
  model: ProductModel | null;
  busy: boolean;
  productName: string;
  onDerive: () => void | Promise<void>;
  onRevise: (edit: ProductModelEdit) => void | Promise<void>;
}) {
  // Local editable mirror of the bags. Re-seeded during render whenever a new model version lands
  // (keyed by id+version), so the surface reflects the persisted truth and a stale edit-in-progress
  // can't shadow the saved version — without a setState-in-effect cascade. This is React's
  // "adjusting state during render" pattern for derived-from-props local edit buffers.
  const modelKey = model ? `${model.id}@${model.version}` : "none";
  const [seededKey, setSeededKey] = useState(modelKey);
  const [things, setThings] = useState<ProductThing[]>(model?.things ?? []);
  const [relationships, setRelationships] = useState<ProductRelationship[]>(model?.relationships ?? []);
  const [userGoals, setUserGoals] = useState<ProductUserGoal[]>(model?.userGoals ?? []);
  const [states, setStates] = useState<ProductStateElement[]>(model?.states ?? []);

  if (seededKey !== modelKey) {
    setSeededKey(modelKey);
    setThings(model?.things ?? []);
    setRelationships(model?.relationships ?? []);
    setUserGoals(model?.userGoals ?? []);
    setStates(model?.states ?? []);
  }

  const isEmpty = !model
    || (model.things.length + model.relationships.length + model.userGoals.length + model.states.length) === 0;

  // The interpretation-quality indicator — a property of the INTERPRETATION, shown where the
  // interpretation lives. It is explicitly NOT the Context subsystem health number and is never read
  // by the engine.
  const allElements = [...things, ...relationships, ...userGoals, ...states];
  const cited = allElements.filter((el) => el.provenance === "derived").length;
  const speculative = allElements.length - cited;

  // An edit saves the changed bag through ReviseProductModel (its own append-only event log → a new
  // version), then the parent re-fetches.
  const saveThings = (next: ProductThing[]) => { setThings(next); void onRevise({ things: next }); };
  const saveRelationships = (next: ProductRelationship[]) => { setRelationships(next); void onRevise({ relationships: next }); };
  const saveGoals = (next: ProductUserGoal[]) => { setUserGoals(next); void onRevise({ userGoals: next }); };
  const saveStates = (next: ProductStateElement[]) => { setStates(next); void onRevise({ states: next }); };

  const thingName = (id: string) => things.find((t) => t.id === id)?.name || id;

  return (
    <section className="understanding-surface" aria-labelledby="picture-title">
      <header className="studio-page-head">
        <div>
          <span className="studio-eyebrow">Living product picture · interpretation, not cited truth</span>
          <h1 id="picture-title">{productName}</h1>
          <p>The editable model of your product — its core objects, how they relate, what users are trying to do, and the states they move through. Generated by Claude, edited by you, kept current with real-world signals.</p>
        </div>
        <button className="studio-primary-action" disabled={busy} onClick={() => void onDerive()} type="button">
          {busy ? <LoaderCircle className="spin" /> : <Sparkles />}
          {model ? "Re-derive from code" : "Derive from code"}
        </button>
      </header>

      <div className="understanding-facts">
        <div><span>Version</span><strong>{model ? `v${model.version}` : "—"}</strong></div>
        <div><span>Generated by</span><strong>{model?.generatedBy ?? "—"}</strong></div>
        <div><span>Grounding</span><strong>{cited} cited / {speculative} speculative</strong></div>
        <div><span>Pinned signals</span><strong>{model?.pinnedSignals.length ?? "—"}</strong></div>
      </div>

      {isEmpty ? (
        <button className="understanding-empty" disabled={busy} onClick={() => void onDerive()} type="button">
          <FileCode2 />
          <strong>Derive this product's living picture from grounded reality</strong>
          <span>Reads the scan and a few key files, then proposes the things, relationships, user goals, and states — cited where it can, marked speculative where it's a guess. Yours to edit after.</span>
          <em>Derive from code <ArrowRight /></em>
        </button>
      ) : (
        <div className="pp-columns">
          {/* Things — the core product objects (nouns) */}
          <section className="understanding-panel">
            <header><Boxes /><strong>Things</strong><span className="pp-count">{things.length}</span></header>
            <p className="understanding-panel-note">The product's core objects. Edit a name or summary and it saves as a new version.</p>
            {things.map((thing) => (
              <article className="pp-row" key={thing.id}>
                <div className="pp-row-head">
                  <input
                    className="pp-edit pp-edit-name"
                    value={thing.name}
                    onChange={(e) => setThings(things.map((t) => t.id === thing.id ? { ...t, name: e.target.value } : t))}
                    onBlur={() => saveThings(things)}
                    aria-label="Thing name"
                  />
                  {thing.kind ? <span className="pp-kind">{thing.kind}</span> : null}
                  <ProvenanceTag provenance={thing.provenance} />
                </div>
                <textarea
                  className="pp-edit pp-edit-summary"
                  value={thing.summary}
                  rows={2}
                  placeholder="One plain-English line"
                  onChange={(e) => setThings(things.map((t) => t.id === thing.id ? { ...t, summary: e.target.value } : t))}
                  onBlur={() => saveThings(things)}
                  aria-label="Thing summary"
                />
                {thing.evidence.map((c, i) => (
                  <code className="pp-cite" key={`${c.file}-${c.line}-${i}`}>{c.file}:{c.line}</code>
                ))}
              </article>
            ))}
          </section>

          {/* Relationships — how the things relate */}
          <section className="understanding-panel">
            <header><GitBranch /><strong>Relationships</strong><span className="pp-count">{relationships.length}</span></header>
            <p className="understanding-panel-note">How the things relate.</p>
            {relationships.length === 0 ? (
              <div className="studio-empty">No relationships in this version.</div>
            ) : relationships.map((rel) => (
              <article className="pp-row" key={rel.id}>
                <div className="pp-row-head">
                  <span className="pp-rel">{thingName(rel.from)}</span>
                  <input
                    className="pp-edit pp-edit-label"
                    value={rel.label}
                    onChange={(e) => setRelationships(relationships.map((r) => r.id === rel.id ? { ...r, label: e.target.value } : r))}
                    onBlur={() => saveRelationships(relationships)}
                    aria-label="Relationship label"
                  />
                  <span className="pp-rel">{thingName(rel.to)}</span>
                  <ProvenanceTag provenance={rel.provenance} />
                </div>
                {rel.summary ? <p className="pp-summary">{rel.summary}</p> : null}
              </article>
            ))}
          </section>

          {/* User goals — what users are trying to accomplish */}
          <section className="understanding-panel">
            <header><Target /><strong>User goals</strong><span className="pp-count">{userGoals.length}</span></header>
            <p className="understanding-panel-note">What users are trying to accomplish.</p>
            {userGoals.length === 0 ? (
              <div className="studio-empty">No user goals in this version.</div>
            ) : userGoals.map((g) => (
              <article className="pp-row" key={g.id}>
                <div className="pp-row-head">
                  {g.actor ? <span className="pp-kind">{g.actor}</span> : null}
                  <ProvenanceTag provenance={g.provenance} />
                </div>
                <textarea
                  className="pp-edit pp-edit-summary"
                  value={g.goal}
                  rows={2}
                  onChange={(e) => setUserGoals(userGoals.map((x) => x.id === g.id ? { ...x, goal: e.target.value } : x))}
                  onBlur={() => saveGoals(userGoals)}
                  aria-label="User goal"
                />
              </article>
            ))}
          </section>

          {/* States — key states a core object moves through */}
          <section className="understanding-panel">
            <header><Workflow /><strong>States</strong><span className="pp-count">{states.length}</span></header>
            <p className="understanding-panel-note">Key states a core object moves through.</p>
            {states.length === 0 ? (
              <div className="studio-empty">No states in this version.</div>
            ) : states.map((s) => (
              <article className="pp-row" key={s.id}>
                <div className="pp-row-head">
                  <input
                    className="pp-edit pp-edit-name"
                    value={s.name}
                    onChange={(e) => setStates(states.map((x) => x.id === s.id ? { ...x, name: e.target.value } : x))}
                    onBlur={() => saveStates(states)}
                    aria-label="State name"
                  />
                  {s.thingId ? <span className="pp-kind">{thingName(s.thingId)}</span> : null}
                  <ProvenanceTag provenance={s.provenance} />
                </div>
                {s.summary ? <p className="pp-summary">{s.summary}</p> : null}
              </article>
            ))}
          </section>

          {/* Pinned signals — the "living" layer: real-world feedback joined back onto the picture */}
          <section className="understanding-panel pp-panel-wide">
            <header><Radio /><strong>Pinned signals</strong><span className="pp-count">{model?.pinnedSignals.length ?? 0}</span></header>
            <p className="understanding-panel-note">Real-world feedback pinned onto an element — the living layer that keeps the picture current. Signals arrive from runs and the world, not founder edits.</p>
            {(model?.pinnedSignals.length ?? 0) === 0 ? (
              <div className="studio-empty">No real-world signals pinned yet. They land here as runs and outcomes accumulate.</div>
            ) : model?.pinnedSignals.map((sig) => (
              <article className="evidence-row" key={sig.id}>
                <span>{sig.type}</span>
                <code>{sig.target.kind}{sig.target.id ? `:${sig.target.id}` : ""}</code>
                <p>{sig.summary || "(no summary)"}</p>
              </article>
            ))}
          </section>
        </div>
      )}
    </section>
  );
}
