export const CROKI_CANVAS_MODEL_ERROR_MESSAGE: Readonly<Record<string, string>> = {
  "duplicate-edge": "That relationship already exists.",
  "duplicate-reference": "That evidence reference is already attached.",
  "edge-limit": "The Canvas relationship limit has been reached.",
  "invalid-body": "The item details exceed the Canvas limit.",
  "invalid-product": "The product name exceeds the Canvas limit.",
  "invalid-reference": "Enter a portable file path or an HTTP(S) URL.",
  "invalid-relation": "Enter a shorter relationship.",
  "invalid-title": "Enter a title within the Canvas limit.",
  "invalid-release": "The release candidate contains invalid or incomplete information.",
  "missing-release": "Start a release candidate before adding work.",
  "missing-release-item": "That release item no longer exists.",
  "missing-release-criterion": "That acceptance criterion no longer exists.",
  "release-item-limit": "The release candidate item limit has been reached.",
  "duplicate-release-item": "That release item already exists.",
  "release-thread-limit": "This item has reached its source Thread limit.",
  "release-criterion-limit": "This item has reached its acceptance-criterion limit.",
  "duplicate-release-criterion": "That acceptance criterion already exists.",
  "release-verification-required": "Pass every acceptance criterion before verifying this item.",
  "missing-node": "That Canvas item no longer exists.",
  "node-limit": "The Canvas item limit has been reached.",
  "reference-limit": "This item has reached the evidence reference limit.",
  "self-edge": "An item cannot relate to itself.",
};
